### ISSUE TITLE
[PE-D][Tester F] Insufficient spacing and padding between command outputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W14-3/tp#137]
![image.png](https://raw.githubusercontent.com/nickczh/ped/main/files/465f944e-0f56-4831-a627-1cdede9d4af3.png)

Will it be better to improved the output formatting by introducing more spaces for better readability?

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: nickczh/ped#8

**Comment by fungg0** [comment]
it will not be better sorry

**Comment by dextboy** [comment]
Hi, unfortunately the team disagrees that this is a feature flaw. Adding spaces for better readability not only is an opinion rather than a flaw, but also introduces potential bugs such as resizing issues. While the team will not be moving forward with this, I do appreciate your diligence in looking out for bugs!
